"""EXPERIMENT 3b — Run the local LLM arbiter over all four prompt conditions.

Uses REAL open-weight models (Qwen3-14B and Qwen3-8B) run locally: no LLM API key is
available in this environment, so all chain-of-thought is generated by genuine model
inference, never simulated.

Batched greedy decoding is the primary run (deterministic given the checkpoint).  Two
additional sampled runs (temperature 0.7) on the two chain-of-thought conditions quantify
the run-to-run stochasticity that VenusRAR flagged for Qwen3-class auditors.

Outputs: results/e3_generations.jsonl (append-only, resumable)
"""
import os, sys, json, time, argparse, re
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from config import RESULTS, LOGS, FAM_NAMES, SEED

WEIGHT_RE = re.compile(r"WEIGHTS:\s*(.*)", re.IGNORECASE | re.DOTALL)


def parse_weights(text):
    """Extract the WEIGHTS line. Returns (dict|None, status)."""
    m = WEIGHT_RE.findall(text)
    if not m:
        return None, "no_weights_line"
    seg = m[-1].split("\n")[0]
    got = dict(re.findall(r"([A-Za-z_]+)\s*=\s*(-?\d+(?:\.\d+)?)", seg))
    w = {}
    for f in FAM_NAMES:
        if f in got:
            w[f] = float(got[f])
    if len(w) < len(FAM_NAMES):
        return (w if w else None), f"partial_{len(w)}/{len(FAM_NAMES)}"
    if sum(w.values()) <= 0:
        return None, "all_zero"
    return w, "ok"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="Qwen/Qwen3-14B")
    ap.add_argument("--gpu", default="0")
    ap.add_argument("--conditions", default="conflict_cot,conflict_direct,cot_only,direct_only")
    ap.add_argument("--seeds", default="0")           # 0 == greedy
    ap.add_argument("--batch", type=int, default=24)
    ap.add_argument("--out", default="e3_generations.jsonl")
    ap.add_argument("--limit", type=int, default=0)
    args = ap.parse_args()

    os.environ["CUDA_VISIBLE_DEVICES"] = args.gpu
    os.environ.setdefault("HF_HOME", str(Path(__file__).resolve().parent.parent / "hf_cache"))
    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer

    prompts = json.load(open(RESULTS / "e3_prompts.json"))
    outp = RESULTS / args.out
    done = set()
    if outp.exists():
        for line in open(outp):
            try:
                r = json.loads(line)
                done.add((r["model"], r["condition"], r["DMS_id"], r["seed"]))
            except Exception:
                pass
    print(f"[e3b] {len(done)} generations already on disk -> resuming")

    tok = AutoTokenizer.from_pretrained(args.model)
    tok.padding_side = "left"
    if tok.pad_token is None:
        tok.pad_token = tok.eos_token
    model = AutoModelForCausalLM.from_pretrained(args.model, dtype=torch.bfloat16,
                                                 device_map="cuda:0")
    model.eval()
    print(f"[e3b] loaded {args.model} on GPU {args.gpu}")

    SYS = ("You are an expert computational protein engineer. You allocate trust across "
           "families of protein fitness predictors. You always end your answer with the "
           "requested WEIGHTS line and nothing after it.")

    jobs = []
    for cond in args.conditions.split(","):
        ids = sorted(prompts[cond])
        if args.limit:
            ids = ids[: args.limit]
        for seed in [int(s) for s in args.seeds.split(",")]:
            for dms in ids:
                if (args.model, cond, dms, seed) in done:
                    continue
                jobs.append((cond, dms, seed))
    print(f"[e3b] {len(jobs)} generations to run")
    if not jobs:
        return

    # Chunk strictly within (condition, seed) groups: max_new_tokens and sampling settings
    # are per-condition, so a mixed batch would truncate CoT answers at the direct-answer cap.
    groups = {}
    for c, d, s in jobs:
        groups.setdefault((c, s), []).append((c, d, s))
    chunks = [g[i: i + args.batch] for g in groups.values()
              for i in range(0, len(g), args.batch)]

    f = open(outp, "a")
    t0 = time.time()
    ntok = 0
    ndone = 0
    for chunk in chunks:
        texts = [tok.apply_chat_template(
            [{"role": "system", "content": SYS},
             {"role": "user", "content": prompts[c][d]}],
            tokenize=False, add_generation_prompt=True, enable_thinking=False)
            for c, d, s in chunk]
        enc = tok(texts, return_tensors="pt", padding=True).to("cuda:0")
        # Any condition whose name contains "cot" is a chain-of-thought condition and needs
        # the long generation budget.  (Suffixed variants like `conflict_cot_shuf` must match.)
        is_cot = "cot" in chunk[0][0]
        mx = 600 if is_cot else 96
        seed = chunk[0][2]
        gen_kw = dict(max_new_tokens=mx, pad_token_id=tok.pad_token_id)
        if seed == 0:
            gen_kw.update(do_sample=False)
        else:
            torch.manual_seed(SEED + seed)
            gen_kw.update(do_sample=True, temperature=0.7, top_p=0.9)
        with torch.no_grad():
            out = model.generate(**enc, **gen_kw)
        new = out[:, enc.input_ids.shape[1]:]
        ntok += int((new != tok.pad_token_id).sum())
        for (cond, dms, sd), row in zip(chunk, new):
            txt = tok.decode(row, skip_special_tokens=True)
            w, status = parse_weights(txt)
            f.write(json.dumps({"model": args.model, "condition": cond, "DMS_id": dms,
                                "seed": sd, "text": txt, "weights": w,
                                "parse_status": status}) + "\n")
        f.flush()
        ndone += len(chunk)
        el = time.time() - t0
        pct = ndone / len(jobs)
        print(f"  [{ndone}/{len(jobs)}] {el:.0f}s  "
              f"{ntok/el:.0f} tok/s  ETA {el/pct-el:.0f}s", flush=True)
    f.close()
    print(f"[e3b] DONE {len(jobs)} generations in {time.time()-t0:.0f}s")


if __name__ == "__main__":
    main()
